[package]
name = "lucle"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
axum = "0.6.8"
ftp = "3.0.1"
diesel = { version = "2.0.3", features = ["mysql", "postgres", "sqlite", "r2d2"] }
diesel_migrations = "2.0.0"
prost = "0.11"
tokio = { version = "1.24", features = ["full"] }
tonic = "0.8.3"
tonic-web = "0.5.0"
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
tower-http = { version = "0.3.5", features = ["fs", "trace", "cors"] }
tracing = "0.1"
url = "2.2.2"

[build-dependencies]
tonic-build = { version = "0.8.4", features = ["prost"] } 
prost-build = "0.11"
