[package]
name = "lucle"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
axum = "0.6.20" 
axum-server = { version = "0.5", features = ["tls-rustls"] }
chrono = { version = "0.4.24", default-features = false, features = ["clock", "std"] }
ftp = "3.0.1"
diesel = { version = "2.1.1", features = ["postgres", "mysql", "chrono", "sqlite", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.0.0"
diffy = "0.3.0"
prost = "0.12"
tokio = { version = "1.27", features = ["full"] }
tokio-rustls = "0.25.0"
tonic = { version = "0.10.2", features = ["transport", "tls"] }
tonic-web = "0.10.2"
tokio-stream = "0.1"
heck = "0.4.0"
hyper = "1.0"
hyper-rustls = { version = "0.27.0", features = ["http2"]}
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
tower = "0.4"
tower-http = { version = "0.4.0", features = ["fs", "trace", "cors", "add-extension", "util"] }
tracing = "0.1"
url = "2.2.2"
toml = "0.8.2"
serde = { version = "1.0.0", features = ["derive"] }
serde_regex = "1.1"
regex = "1.0.6"
syn = { version = "2", features = ["visit"] }
libsqlite3-sys = { version = "0.27.0", features = ["bundled"] } 
pki-types = { package = "rustls-pki-types", version = "1" }
rcgen = "0.12.0"
rustls-pemfile = "2.0.0"
rustls-acme = { git = "https://github.com/ludea/rustls-acme", branch = "tokio_util", features = ["axum"] }
argon2 = "0.5.2"
#rustls-acme = { version = "0.7.6", features = ["axum", "tokio"] }
lettre = { version = "0.11.1", features = ["file-transport"] }
jsonwebtoken = "9.1.0"
email-address-parser = "2.0.0"
diesel_logger = { git = "https://github.com/weiznich/diesel-logger/", branch = "multiconnection_compatibility" }
dlopen2 = "0.6.1"
minisign-verify = "0.2.1"
tera = "1.19.1"
futures-util = "0.3.29"
rustls-native-certs = "0.7.0"
hyper-util = "0.1.1"
tower-service = "0.3.2"
time = "0.3.30"

[build-dependencies]
tonic-build = { version = "0.10.0", features = ["prost"] } 
prost-build = "0.12"
protox = "0.5.1"
