[package]
name = "lucle"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.1"
ftp = "3.0.1"
#rocket = { version = "0.5.0-rc.2", features = ["json"] }
#rocket_cors = { git = "https://github.com/lawliet89/rocket_cors" }
diesel = { version = "2.0.2", features = ["mysql", "postgres", "sqlite", "r2d2"] }
diesel_migrations = "2.0.0"
prost = "0.11"
tokio = { version = "1.0", features = ["full"] }
tonic = "0.8.3"
tonic-web = "0.5.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tower-http = { version = "0.3.0", features = ["fs", "trace", "cors"] }
tracing = "0.1"
url = "2.2.2"

[build-dependencies]
tonic-build = { version = "0.8.0", features = ["prost"] } 
prost-build = "0.11"
