[target.aarch64-unknown-linux-musl]
pre-build = ['apt update && apt install -y zip && curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v22.2/protoc-22.2-linux-x86_64.zip && unzip protoc-22.2-linux-x86_64.zip -d $HOME/.local && export PATH="$PATH:$HOME/.local/bin"']

