apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lucle
  namespace: lucle
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`your.example.com`)
    kind: Rule
    services:
    - name: lucle
      port: 8080
