{{- if .Values.ingressroute.enabled -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lucle
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`{{ .Values.ingressroute.host }}`) 
    kind: Rule
    services:
    - name: lucle
      port: 8080
  {{- if .Values.ingressroute.tls }}
  tls:
    {{- range .Values.ingressroute.tls }}
    secretName: {{ .secretName }}
    certResolver: {{ .certResolver }}
    {{- end }}
  {{- end }}
{{- end }}
