apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: lucleingressroute
  namespace: default
spec:
  entryPoints:
    - http
  routes:
  - match: Host(`your.example.com`)
    kind: Rule
    services:
    - name: lucle
      port: 80
