name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install protoc
      run: |
        curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v22.2/protoc-22.2-linux-x86_64.zip
        unzip protoc-22.2-linux-x86_64.zip -d $HOME/.local
        export PATH="$PATH:$HOME/.local/bin"
    - name: Install dependencies
      run: cd web && yarn install
 #   - name: lint
 #     run: cd web && yarn lint
#    - name: prettier
 #     run: cd web && yarn prettier
    - name: Build frontend (js side)
      run: cd web && yarn build
    - name: Build backend (rust side)
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  build-aarch64:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:   
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build container 
      uses: docker/build-push-action@v4
      with:
        load: true
        push: false
        tags: |
          ludea/lucle:latest
        platforms: linux/arm64
        target: alpine
    - name: get binary
      run: |
        docker container ls --all
        docker run ludea/lucle:latest
    - uses: actions/upload-artifact@v3
      with:
       name: lucle
       path: lucle
      
