name: Release

on: 
 push:
   tags:
     - chart-v*
 
jobs:     
  build-helm-chart:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - id: 'configure-git'
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.4.0
        
      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.5.0

      - name: Run chart-testing (install)
        run: |
          kubectl apply -f https://raw.githubusercontent.com/traefik/traefik/v2.9/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
          ct install --chart-dirs chart/ --charts chart/ --debug

      - name: Get version
        uses: mikefarah/yq@v4.34.1
        with:
          cmd: echo "VERSION=$(yq .version chart/Chart.yaml)" >> $GITHUB_ENV
        
      - name: Package chart
        run: helm package chart/

      - name: Push
        uses: cloudsmith-io/action@v0.5.3
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "helm"
          owner: "ludea"
          repo: "lucle"
          republish: "true"
          file: lucle-${{ env.VERSION }}.tgz
